apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/launch-stage: BETA
  labels:
    cloud.googleapis.com/location: asia-northeast1
  name: nginx-php-fpm-example
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/execution-environment: gen1
    spec:
      containerConcurrency: 80
      containers:
      - name: nginx
        image: 【Nginxのイメージ】
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
        ports:
          - name: http1
            containerPort: 80
        env:
          - name: TEST
            value: Nginx TEST NOW!
      - name: php
        image: 【PHPのイメージ】
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
        env:
          - name: TEST
            value: PHP TEST NOW!
